### ISSUE TITLE
Typo in chapter2/README.md

### ISSUE THREAD

**Issue by zanesewell** [mreferre/aws-proton-tutorial#5]
Line 131 is currently written as the following
`{% if 'VPC-ECSCluster-Env-Test' in environment.name %}`

Should be updated to
`{% if 'VPC-ECSCluster-Env-Test' in service_instance.environment.name %}`

**Comment by mreferre** [comment]
Thanks for reporting this! Are you suggesting that `environment.name` doesn't work? I am pretty sure I tested this (more than once) and it worked just fine. `environment.name` should contain the name of the environment (which is what we need to match). Doesn't `service_instance.environment.name` return the name of the instance I am deploying? That would not (and would never) match `VPC-ECSCluster-Env-Test`. 

Can you clarify? Thanks!

**Comment by zanesewell** [comment]
Yes sorry I should have been more clear. I get the following error when deploying with `environment.name`
`RenderingException - There was an issue rendering the provided template. 'environment' is undefined in pipeline_infrastructure/cloudformation.yaml`

After prepending with `service.environment` it deploys and functions as expected.

**Comment by mreferre** [comment]
Fixed it in this commit: https://github.com/mreferre/aws-proton-tutorial/commit/b88159c44027589517ef616085e1276cb5ac950c
